import {
  uploadImage,
  deleteImage,
  createArticle,
  getArticleById,
  updateArticle,
  deleteArticle,
  getFeaturedArticles,
  getLatestArticles,
  getComplementaryArticles,
  getArticlesByCategory,
  getArticlesBySubcategory,
  searchArticles,
  getAllArticles,
  getFeaturedArticlesByCategory,
  getAllArticlesForSearch,
  checkAndDeleteExpiredArticles,
} from "./articleFunctions"; // Importamos las funciones modularizadas

export {
  uploadImage,
  deleteImage,
  createArticle,
  getArticleById,
  updateArticle,
  deleteArticle,
  getFeaturedArticles,
  getLatestArticles,
  getComplementaryArticles,
  getArticlesByCategory,
  getArticlesBySubcategory,
  searchArticles,
  getAllArticles,
  getFeaturedArticlesByCategory,
  getAllArticlesForSearch,
  checkAndDeleteExpiredArticles,
};
